spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8181
          predicates:
            - Path=/order/**
          filters:
            - CustomAuthFilter
